CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(30)                             NOT NULL,
    uri       VARCHAR(30)                             NOT NULL,
    ip        VARCHAR(15)                             NOT NULL,
    timestamp TIMESTAMP                               NOT NULL
);